---
title: "les chômeurs par niveau d'éducation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
---
title: "cartogaphie "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)

library(raster)
library(leaflet)
library(shiny)
tnMAPDELE<- getData(name="GADM",  country="TUN", level=2)

```

Cartographie
=====================================  


Column {data-width=400}
-----------------------------------------------------------------------


###pourcentage des chômeur avec un niveau d'étude en primaire 

```{r}
var=7
library(readxl)

Code <- read_excel("Code Delegation Tunisie.xlsx")

stage <- read_excel("stage.xlsx")
  i=match(stage$Régions,Code$Régions)
 mm=NULL
  dataB<- cbind.data.frame(stage,Code[i,"HASC"])

   l=match(tnMAPDELE$HASC_2,dataB$HASC)
  
  dataB<- cbind.data.frame(dataB[l,],tnMAPDELE)
dataB[is.na(dataB[,var]),var]=0

c="%"

 labels<-sprintf("<strong>%s<br/><strong>%g<br/><strong>%s<br/>",dataB[,"NAME_2"],dataB[,var],dataB[,"NAME_1"])
  labels<-paste(labels)%>%lapply(htmltools::HTML)
  col<-colorRampPalette(c("blue","gray","white","red","black"))
  pal <- colorNumeric(col(268),domain = dataB[,var],n=268)
 
   mm=leaflet(data = tnMAPDELE) %>%addProviderTiles(providers$Esri.WorldImagery)%>% addPolygons(data=tnMAPDELE,
                       fillColor=~pal(dataB[,var]),
                       fillOpacity=10,
                       col="black",
                       weight=1.1,
                       opacity=0.7,
                       highlight=highlightOptions(weight=4.0,
                                                  color="#FFFFFF",
                                                  fillOpacity = 0.7,
                                                  bringToFront = TRUE),
                       label=labels,
                       labelOptions=labelOptions( style = list("font-weight" = "normal",
                                                               padding = "3px 8px"),
                                                  textsize = "15px",
                                                  direction = "auto"))%>%addLegend(data=dataB,
                       pal=pal,
                       values=~dataB[,var],
                       opacity=1.5,
                       title = colnames(dataB)[var])

   mm
```

Column {data-width=400}
-----------------------------------------------------------------------

### pourcentage des chômeur avec un niveau d'étude en secondaire 

```{r}
var1=8

 labels<-sprintf("<strong>%s<br/> <strong>%g<br/><strong>%s<br/>",dataB[,"NAME_2"],dataB[,var1],dataB[,"NAME_1"])
  labels<-paste(labels)%>%lapply(htmltools::HTML)
  col<-colorRampPalette(c("blue","gray","white","red","black"))
  pal <- colorNumeric(col(268),domain = dataB[,var1],n=268)
 mm=leaflet(data = tnMAPDELE) %>%addProviderTiles(providers$Esri.WorldImagery)%>% addPolygons(data=tnMAPDELE,
                       fillColor=~pal(dataB[,var1]),
                       fillOpacity=10,
                       col="black",
                       weight=1.1,
                       opacity=0.7,
                       highlight=highlightOptions(weight=4.0,
                                                  color="#FFFFFF",
                                                  fillOpacity = 0.7,
                                                  bringToFront = TRUE),
                       label=labels,
                       labelOptions=labelOptions( style = list("font-weight" = "normal",
                                                               padding = "3px 8px"),
                                                  textsize = "15px",
                                                  direction = "auto"))%>%addLegend(data=dataB,
                       pal=pal,
                       values=~dataB[,var1],
                       opacity=1.5,
                       title = colnames(dataB)[var1])

 mm  
```



Column {data-width=400}
-----------------------------------------------------------------------

### pourcentage des chômeur avec un niveau d'étude universitaire 


```{r}

var1=9


 labels<-sprintf("<strong>%s<br/> <strong>%g<br/><strong>%s<br/>",dataB[,"NAME_2"],dataB[,var1],dataB[,"NAME_1"])
  labels<-paste(labels)%>%lapply(htmltools::HTML)
  col<-colorRampPalette(c("blue","gray","white","red","black"))
  pal <- colorNumeric(col(268),domain = dataB[,var1],n=268)

 mm=leaflet(data = tnMAPDELE) %>%addProviderTiles(providers$Esri.WorldImagery)%>% addPolygons(data=tnMAPDELE,
                       fillColor=~pal(dataB[,var1]),
                       fillOpacity=10,
                       col="black",
                       weight=1.1,
                       opacity=0.7,
                       highlight=highlightOptions(weight=4.0,
                                                  color="#FFFFFF",
                                                  fillOpacity = 0.7,
                                                  bringToFront = TRUE),
                       label=labels,
                       labelOptions=labelOptions( style = list("font-weight" = "normal",
                                                               padding = "3px 8px"),
                                                  textsize = "15px",
                                                  direction = "auto"))%>%addLegend(data=dataB,
                       pal=pal,
                       values=~dataB[,var1],
                       opacity=1.5,
                       title = colnames(dataB)[var1])

 mm 
```

Graphes
=====================================  
Column {data-width=400}
-----------------------------------------------------------------------

```{r}
library(ggpubr)
ggboxplot(dataB,
          y = c("perprim", "persec", "persup"),
          combine = TRUE,
          palette = "jco",
          ylab = "Pourcentage", 
          add = "jitter",                           # Add jittered points
          add.params = list(size = 0.1, jitter = 0.2)  # Point size and the amount of jittering
)
```


Column {data-width=400}
-----------------------------------------------------------------------

```{r}
 ggdensity(dataB,
         x = c("perprim", "persec", "persup"),
           palette = "jco",
          add = "median", 
         combine = T,
       
         rug = TRUE,
         ylab="pourcentage",na.rm = TRUE)
```

Data
====================================

```{r}

library(DT)
datatable(dataB[1:294,1:10],rownames = F,colnames = colnames(dataB[,1:10]))

```

